### ISSUE TITLE
Official Roademap

### ISSUE THREAD

**Issue by Felli** [GreenVolume/windows-10-desktop-app#2]
# Roadmap

## Codebase
- [ ] Refactor codebase
- [ ] Implement native look and feel with webview

## Features
- [ ] Implement app report button.
- [ ] Refresh button for windows mobile.
- [ ] Use on desktop

## Support Options
- [x] Email
- [x] Forums
- [ ] Docs
